import type {Metadata} from "next";
import "@/app/globals.css";
import {Quicksand} from "next/font/google";
import Layout from "@/components/layouts"

const quicksand = Quicksand({subsets: ["latin"], weight: ["400", "500", "700"]});

export const metadata: Metadata = {
    title: "Blog",
    description: "Generated by create next app",
};

export default function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <div className={quicksand.className}>
            <Layout>
                {children}
            </Layout>
        </div>
    );
}
