import type {Metadata} from "next";
import "@/app/globals.css";
import {Oswald} from "next/font/google";

const oswald = Oswald({subsets: ["latin"], weight: ["400", "500", "700"]});

export const metadata: Metadata = {
    title: "Celil Akdemir",
    description: "Generated by create next app",
};

export default function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <html lang="en">
        <body
            className={oswald.className}
        >
            {children}
        </body>
        </html>
    );
}
