import type {Metadata} from "next";
import "@/app/globals.css";
// import {Quicksand} from "next/font/google";
import { Inria_Sans } from "next/font/google";


// const quicksand = Quicksand({subsets: ["latin"], weight: ["400", "500", "700"]});

const inriaSans = Inria_Sans({
    subsets: ["latin"],
    weight: ["400", "400", "700"],
    variable: "--font-inria",
});

export const metadata: Metadata = {
    title: "Blog",
    description: "Generated by create next app",
};

export default function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <div className="flex flex-col h-screen w-screen">
            <div className={`${inriaSans.variable} font-sans`}>
                {children}
            </div>
        </div>
    );
}
